### ISSUE TITLE
`claim` does not set token count

### ISSUE THREAD

**Issue by friedger** [bitcoin-nfts/stacks-svg#4]
In contract stacks-svg-nft.clar,
mint-many and transfer sets the token count correctly, but `claim` does not.

**Comment by LNow** [comment]
It does. Indirectly in `mint-many` function:
https://github.com/bitcoin-nfts/stacks-svg/blob/057c823b6b5e188816cd8b96541cfac004fb2cd5/contracts/stacks-svg-nft.clar#L132

**Comment by friedger** [comment]
Thanks for the clarification. I mixed things up with mint-many-iter.
